transform-score-global
wilgert/browser-quiz-class32 pull request #12
Opened 2021-06-02 11:16 UTC by mohammadalnajar

2021-06-02 11:34 UTC, wilgert requested changes

2021-06-02 11:34 UTC, wilgert commented on src/views/createQuestionElement.js
> +const score = createDOMElement('h3', { id: 'user-score' });
why does this element have to be created outside the function?

2021-06-02 21:57 UTC, mohammadalnajar commented on src/views/createQuestionElement.js
> +const score = createDOMElement('h3', { id: 'user-score' });
Fixed
Now it is better I think

2021-06-03 06:15 UTC, wilgert commented on src/handlers/handleNextQuestion.js
> +      document.body.appendChild(score);
why do you first get the score element from the dom and then append it again?

2021-06-03 06:59 UTC, merged